#!/usr/bin/env node
// Builds the Android app's web content from the Mac app's screens:
//   node scripts/assemble-web.js [outDir]   (default app/src/main/assets)
// - web/: soundboard-mac/src/renderer, plus the Android layer (web/*) and the
//   Mac's store modules (src/library.js, …) wrapped for node-shim.js.
// - ambience/: the built-in loops.
// Run it before building the app (the Gradle build runs it too).
const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '../..');
const mac = path.join(repo, 'soundboard-mac/src');
const android = path.resolve(__dirname, '..');
const out = path.resolve(process.argv[2] || path.join(android, 'app/src/main/assets'));
const web = path.join(out, 'web');

fs.rmSync(web, { recursive: true, force: true });
fs.mkdirSync(web, { recursive: true });
fs.cpSync(path.join(mac, 'renderer'), web, { recursive: true });
fs.rmSync(path.join(out, 'ambience'), { recursive: true, force: true });
fs.cpSync(path.join(mac, 'ambience'), path.join(out, 'ambience'), { recursive: true });

// The Mac's store modules, as modules for node-shim.js's require().
const modules = ['library', 'bashes', 'kits', 'bookmarks', 'icon-ids', 'renderer/icons'];
const wrapped = modules.map((name) => {
  const source = fs.readFileSync(path.join(mac, `${name}.js`), 'utf8');
  return `DRNode.define(${JSON.stringify(name)}, function (module, exports, require) {\n${source}\n});`;
});
fs.writeFileSync(path.join(web, 'modules.js'), `// Generated by scripts/assemble-web.js from soundboard-mac/src. Don't edit.\n${wrapped.join('\n\n')}\n`);

// The dice's 3D libraries, from the Mac app's node_modules (run npm install there first).
const vendor = path.join(web, 'vendor');
fs.mkdirSync(vendor, { recursive: true });
const modulesDir = path.join(repo, 'soundboard-mac/node_modules');
for (const file of ['three/build/three.module.js', 'three/build/three.core.js', 'cannon-es/dist/cannon-es.js']) {
  fs.copyFileSync(path.join(modulesDir, file), path.join(vendor, path.basename(file)));
}
const dice = path.join(web, 'dice.js');
fs.writeFileSync(dice, fs.readFileSync(dice, 'utf8')
  .replace("'../../node_modules/three/build/three.module.js'", "'./vendor/three.module.js'")
  .replace("'../../node_modules/cannon-es/dist/cannon-es.js'", "'./vendor/cannon-es.js'"));

for (const file of fs.readdirSync(path.join(android, 'web'))) {
  fs.copyFileSync(path.join(android, 'web', file), path.join(web, file));
}

// Sounds come from the app's own file server on this phone (127.0.0.1).
const csp = "default-src 'self'; media-src 'self' http://127.0.0.1:* blob:; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'";
function adapt(file, scripts) {
  const target = path.join(web, file);
  let html = fs.readFileSync(target, 'utf8');
  html = html.replace(/<meta http-equiv="Content-Security-Policy" content="[^"]*">/, `<meta http-equiv="Content-Security-Policy" content="${csp}">`);
  html = html.replace('<html lang="en">', '<html lang="en" class="android">');
  html = html.replace('<meta name="viewport"', '<meta name="viewport-mac"');
  html = html.replace('</head>', '  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">\n  <link rel="stylesheet" href="android.css">\n</head>');
  // The Android layer goes before the Mac screens' own scripts.
  const first = html.indexOf('<script src=');
  if (first < 0) throw new Error(`No scripts in ${file}`);
  html = html.slice(0, first) + scripts.map((s) => `<script src="${s}"></script>\n  `).join('') + html.slice(first);
  fs.writeFileSync(target, html);
}
adapt('index.html', ['node-shim.js', 'modules.js', 'android-main.js', 'android-ui.js']);
adapt('bash-editor.html', ['android-editor.js']);
console.log(`Assembled ${path.relative(process.cwd(), web)}`);
