const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('soundboard', {
  list: () => ipcRenderer.invoke('sounds:list'),
  importDialog: () => ipcRenderer.invoke('sounds:import-dialog'),
  add: (sound) => ipcRenderer.invoke('sounds:add', sound),
  update: (id, changes) => ipcRenderer.invoke('sounds:update', id, changes),
  remove: (id) => ipcRenderer.invoke('sounds:remove', id),
  reorder: (ids) => ipcRenderer.invoke('sounds:reorder', ids),
  reveal: (id) => ipcRenderer.invoke('sounds:reveal', id),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
  onHotkey: (callback) => ipcRenderer.on('hotkey:play', (_e, id) => callback(id)),
  readSound: (id) => ipcRenderer.invoke('sounds:read', id),
  kits: {
    list: () => ipcRenderer.invoke('kits:list'),
    create: (options) => ipcRenderer.invoke('kits:create', options),
    update: (id, changes) => ipcRenderer.invoke('kits:update', id, changes),
    addItems: (id, items, sectionId) => ipcRenderer.invoke('kits:add-items', id, items, sectionId),
    removeItem: (id, item, sectionId) => ipcRenderer.invoke('kits:remove-item', id, item, sectionId),
    duplicate: (id) => ipcRenderer.invoke('kits:duplicate', id),
    remove: (id) => ipcRenderer.invoke('kits:remove', id),
    onChanged: (callback) => ipcRenderer.on('kits:changed', (_e, list) => callback(list)),
  },
  editor: {
    setDirty: (dirty) => ipcRenderer.invoke('bash-editor:set-dirty', dirty),
    onCloseRequested: (callback) => ipcRenderer.on('bash-editor:close-requested', () => callback()),
  },
  tags: {
    list: () => ipcRenderer.invoke('tags:list'),
    add: (name) => ipcRenderer.invoke('tags:add', name),
    remove: (name) => ipcRenderer.invoke('tags:remove', name),
  },
  onSoundsChanged: (callback) => ipcRenderer.on('sounds:changed', () => callback()),
  bashes: {
    list: () => ipcRenderer.invoke('bashes:list'),
    get: (id) => ipcRenderer.invoke('bashes:get', id),
    create: (options) => ipcRenderer.invoke('bashes:create', options),
    update: (id, changes) => ipcRenderer.invoke('bashes:update', id, changes),
    duplicate: (id) => ipcRenderer.invoke('bashes:duplicate', id),
    remove: (id) => ipcRenderer.invoke('bashes:remove', id),
    openEditor: (id, options) => ipcRenderer.invoke('bashes:open-editor', id, options),
    pickCover: () => ipcRenderer.invoke('bashes:pick-cover'),
    setCoverData: (id, base64) => ipcRenderer.invoke('bashes:set-cover-data', id, base64),
    coverData: (file) => ipcRenderer.invoke('bashes:cover-data', file),
    onChanged: (callback) => ipcRenderer.on('bashes:changed', (_e, list) => callback(list)),
  },
  ambience: {
    builtins: () => ipcRenderer.invoke('ambience:builtins'),
    readBuiltin: (file) => ipcRenderer.invoke('ambience:read-builtin', file),
    load: () => ipcRenderer.invoke('ambience:load'),
    save: (state) => ipcRenderer.invoke('ambience:save', state),
  },
  live: {
    status: () => ipcRenderer.invoke('live:status'),
    hostStart: (options) => ipcRenderer.invoke('live:host-start', options),
    hostEvent: (event) => ipcRenderer.send('live:host-event', event),
    listen: (options) => ipcRenderer.invoke('live:listen', options),
    leave: () => ipcRenderer.invoke('live:leave'),
    browse: (on) => ipcRenderer.invoke('live:browse', on),
    onStatus: (callback) => ipcRenderer.on('live:status', (_e, status) => callback(status)),
    onCommand: (callback) => ipcRenderer.on('live:command', (_e, command) => callback(command)),
    onSessions: (callback) => ipcRenderer.on('live:sessions', (_e, list) => callback(list)),
    onCue: (callback) => ipcRenderer.on('live:cue', (_e, cue) => callback(cue)),
    onRules: (callback) => ipcRenderer.on('live:rules', (_e, mode) => callback(mode)),
    onCatalog: (callback) => ipcRenderer.on('live:catalog', (_e, items) => callback(items)),
    offer: (ids) => ipcRenderer.invoke('live:offer', ids),
    cue: (request) => ipcRenderer.invoke('live:cue', request),
    notify: (note) => ipcRenderer.send('live:notify', note),
  },
  downloadAudio: (jobId, url) => ipcRenderer.invoke('youtube:download-audio', { jobId, url }),
  cancelDownload: (jobId) => ipcRenderer.invoke('youtube:cancel-download', jobId),
  onDownloadProgress: (callback) => ipcRenderer.on('youtube:download-progress', (_e, jobId, progress) => callback(jobId, progress)),
});
