#!/usr/bin/env python3
"""Copies the YouTube ad blocker from the Mac app (soundboard-mac/src/youtube-preload.js,
between the BEGIN/END AD BLOCKER markers) into the iPad app's AdBlockScript.swift,
so both apps block ads the same way.

Run from the repo root after changing the ad blocker:  python3 tools/sync-adblock.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'soundboard-mac/src/youtube-preload.js'
OUT = ROOT / 'soundboard-ipad/Soundboard.swiftpm/YouTube/AdBlockScript.swift'

text = SOURCE.read_text()
start = text.index('// BEGIN AD BLOCKER')
end = text.index('// END AD BLOCKER') + len('// END AD BLOCKER')
script = text[start:end]
assert '"""#' not in script

OUT.write_text(f'''// Generated by tools/sync-adblock.py from the Mac app's youtube-preload.js. Do not edit by hand.

enum AdBlockScript {{
    /// Injected into YouTube pages before they load while "Block YouTube ads" is on.
    static let source = #"""
{script}
youtubeAdBlocker();
"""#

    /// Ad and ad-tracking servers, blocked while "Block YouTube ads" is on (WebKit content rules: simple patterns only, no alternation).
    static let contentRules = #"""
[
  {{"trigger": {{"url-filter": "^https?://[^/]*doubleclick\\\\.net/"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://[^/]*googlesyndication\\\\.com/"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://[^/]*googleadservices\\\\.com/"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://www\\\\.youtube\\\\.com/pagead/"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://www\\\\.youtube\\\\.com/api/stats/ads"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://www\\\\.youtube\\\\.com/get_midroll_"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://www\\\\.youtube\\\\.com/ptracking"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://m\\\\.youtube\\\\.com/pagead/"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://m\\\\.youtube\\\\.com/api/stats/ads"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://m\\\\.youtube\\\\.com/get_midroll_"}}, "action": {{"type": "block"}}}},
  {{"trigger": {{"url-filter": "^https?://m\\\\.youtube\\\\.com/ptracking"}}, "action": {{"type": "block"}}}}
]"""#
}}
''')
print(f'Wrote {OUT.relative_to(ROOT)}')
