// Generated by tools/generate-ios-icons.py from the Mac app's icons.js. Do not edit by hand.

enum IconData {
    static let all: [IconDefinition] = [
        IconDefinition(id: "sword", name: "Sword", category: "Combat", shapes: [
            IconShape(path: "M 20 4 L 19 8 L 8.5 18.5 L 5.5 15.5 L 16 5 Z"),
            IconShape(path: "M 4 14 L 10 20"),
            IconShape(path: "M 6.5 17.5 L 3.5 20.5"),
        ]),
        IconDefinition(id: "crossed-swords", name: "Crossed swords", category: "Combat", shapes: [
            IconShape(path: "M 4 4 L 15 15 M 20 4 L 9 15"),
            IconShape(path: "M 4 4 L 7 4 M 4 4 L 4 7 M 20 4 L 17 4 M 20 4 L 20 7"),
            IconShape(path: "M 13 17 L 17 13 M 7 13 L 11 17"),
            IconShape(path: "M 16 16 L 19.5 19.5 M 8 16 L 4.5 19.5"),
        ]),
        IconDefinition(id: "dagger", name: "Dagger", category: "Combat", shapes: [
            IconShape(path: "M 12 2 L 14 5 L 14 14 L 10 14 L 10 5 Z"),
            IconShape(path: "M 8 14 L 16 14"),
            IconShape(path: "M 12 14 L 12 18"),
            IconShape(path: "M 13.8 20 C 13.8 20.994 12.994 21.8 12 21.8 C 11.006 21.8 10.2 20.994 10.2 20 C 10.2 19.006 11.006 18.2 12 18.2 C 12.994 18.2 13.8 19.006 13.8 20 Z"),
        ]),
        IconDefinition(id: "axe", name: "Battle axe", category: "Combat", shapes: [
            IconShape(path: "M 12 2.5 L 12 22"),
            IconShape(path: "M 12 5.5 C 14.5 5.5 17 4.5 19 3 C 21 6.5 21 11 19 14.5 C 17 13 14.5 12 12 12"),
            IconShape(path: "M 12 5.5 C 9.5 5.5 7 4.5 5 3 C 3 6.5 3 11 5 14.5 C 7 13 9.5 12 12 12"),
        ]),
        IconDefinition(id: "bow", name: "Bow and arrow", category: "Combat", shapes: [
            IconShape(path: "M 8 3 C 15 6 15 18 8 21"),
            IconShape(path: "M 8 3 L 8 21", opacity: 0.6),
            IconShape(path: "M 3 12 L 19 12"),
            IconShape(path: "M 16 9 L 19 12 L 16 15"),
            IconShape(path: "M 3 12 L 2 10 M 3 12 L 2 14 M 5 12 L 4 10 M 5 12 L 4 14"),
        ]),
        IconDefinition(id: "shield", name: "Shield", category: "Combat", shapes: [
            IconShape(path: "M 12 3 L 19 6 L 19 11 C 19 16 15.5 19.5 12 21 C 8.5 19.5 5 16 5 11 L 5 6 Z"),
            IconShape(path: "M 12 8 L 12 16 M 8 12 L 16 12"),
        ]),
        IconDefinition(id: "helmet", name: "Helmet", category: "Combat", shapes: [
            IconShape(path: "M 5 20 L 5 12 C 5 8.134 8.134 5 12 5 C 15.866 5 19 8.134 19 12 L 19 20 Z"),
            IconShape(path: "M 5 13 L 19 13"),
            IconShape(path: "M 12 13 L 12 20"),
            IconShape(path: "M 12 5 L 12 3"),
        ]),
        IconDefinition(id: "hammer", name: "War hammer", category: "Combat", shapes: [
            IconShape(path: "M 4 20 L 14 10"),
            IconShape(path: "M 10 6.5 L 13 3.5 L 20.5 11 L 17.5 14 Z"),
        ]),
        IconDefinition(id: "mace", name: "Mace", category: "Combat", shapes: [
            IconShape(path: "M 12 12 L 12 22"),
            IconShape(path: "M 16 7.5 C 16 9.709 14.209 11.5 12 11.5 C 9.791 11.5 8 9.709 8 7.5 C 8 5.291 9.791 3.5 12 3.5 C 14.209 3.5 16 5.291 16 7.5 Z"),
            IconShape(path: "M 12 2 L 12 3.5 M 7 4 L 8 5 M 17 4 L 16 5 M 5.5 8 L 7 8 M 17 8 L 18.5 8"),
        ]),
        IconDefinition(id: "explosion", name: "Explosion", category: "Combat", shapes: [
            IconShape(path: "M 12 2 L 14 7 L 19 5 L 17 10 L 22 12 L 17 14 L 19 19 L 14 17 L 12 22 L 10 17 L 5 19 L 7 14 L 2 12 L 7 10 L 5 5 L 10 7 Z"),
        ]),
        IconDefinition(id: "fist", name: "Fist", category: "Combat", shapes: [
            IconShape(path: "M 7 11 L 7 8 C 7 7.172 7.672 6.5 8.5 6.5 C 9.328 6.5 10 7.172 10 8 L 10 10 M 10 9 L 10 7 C 10 6.172 10.672 5.5 11.5 5.5 C 12.328 5.5 13 6.172 13 7 L 13 10 M 13 9.5 L 13 8 C 13 7.172 13.672 6.5 14.5 6.5 C 15.328 6.5 16 7.172 16 8 L 16 10.5 M 16 10 C 16 9.172 16.672 8.5 17.5 8.5 C 18.328 8.5 19 9.172 19 10 L 19 14 C 19 18 16 21 12.5 21 C 9 21 6 18.5 6 15 L 6 12.5 C 6 11.672 6.672 11 7.5 11 L 10 11 C 11.105 11 12 11.895 12 13 C 12 14.105 11.105 15 10 15 L 8 15"),
        ]),
        IconDefinition(id: "wand", name: "Magic wand", category: "Magic", shapes: [
            IconShape(path: "M 4 20 L 15 9"),
            IconShape(path: "M 14 8 L 16 10"),
            IconShape(path: "M 18 2 L 18 5 M 16.5 3.5 L 19.5 3.5 M 20 9 L 20 11 M 19 10 L 21 10 M 11 3 L 11 5 M 10 4 L 12 4"),
        ]),
        IconDefinition(id: "staff", name: "Staff", category: "Magic", shapes: [
            IconShape(path: "M 7 22 L 15 8"),
            IconShape(path: "M 19.3 5.5 C 19.3 7.046 18.046 8.3 16.5 8.3 C 14.954 8.3 13.7 7.046 13.7 5.5 C 13.7 3.954 14.954 2.7 16.5 2.7 C 18.046 2.7 19.3 3.954 19.3 5.5 Z"),
            IconShape(path: "M 20.5 2.5 L 19.5 3.5 M 13 3 L 14 4 M 21 9 L 20 8.5"),
        ]),
        IconDefinition(id: "potion", name: "Potion", category: "Magic", shapes: [
            IconShape(path: "M 10 2.5 L 14 2.5"),
            IconShape(path: "M 10.5 2.5 L 10.5 7.7 C 7.291 8.461 5.161 11.504 5.544 14.78 C 5.927 18.055 8.702 20.525 12 20.525 C 15.298 20.525 18.073 18.055 18.456 14.78 C 18.839 11.504 16.709 8.461 13.5 7.7 L 13.5 2.5"),
            IconShape(path: "M 6.5 14.5 L 17.5 14.5"),
        ]),
        IconDefinition(id: "crystal-ball", name: "Crystal ball", category: "Magic", shapes: [
            IconShape(path: "M 19 10 C 19 13.866 15.866 17 12 17 C 8.134 17 5 13.866 5 10 C 5 6.134 8.134 3 12 3 C 15.866 3 19 6.134 19 10 Z"),
            IconShape(path: "M 7 21 L 17 21 L 15.5 17.7 L 8.5 17.7 Z"),
            IconShape(path: "M 8.8 7.2 C 9.334 6.102 10.388 5.349 11.6 5.2"),
        ]),
        IconDefinition(id: "spellbook", name: "Spellbook", category: "Magic", shapes: [
            IconShape(path: "M 4 19.5 L 4 4.5 C 4 3.672 4.672 3 5.5 3 L 20 3 L 20 18 L 5.5 18 C 4.672 18 4 18.672 4 19.5 C 4 20.328 4.672 21 5.5 21 L 20 21 L 20 18"),
            IconShape(path: "M 12 6.5 L 13 8.5 L 15.2 8.8 L 13.6 10.3 L 14 12.5 L 12 11.5 L 10 12.5 L 10.4 10.3 L 8.8 8.8 L 11 8.5 Z"),
        ]),
        IconDefinition(id: "scroll", name: "Scroll", category: "Magic", shapes: [
            IconShape(path: "M 17 20 L 6.5 20 C 5.119 20 4 18.881 4 17.5 L 4 17 L 15 17 L 15 17.5 C 15 18.881 16.119 20 17.5 20 C 18.881 20 20 18.881 20 17.5 L 20 6 C 20 4.895 19.105 4 18 4 L 8 4 C 6.895 4 6 4.895 6 6 L 6 17"),
            IconShape(path: "M 10 8 L 16 8 M 10 12 L 16 12"),
        ]),
        IconDefinition(id: "sparkle", name: "Sparkle", category: "Magic", shapes: [
            IconShape(path: "M 11 3 C 11.6 7.2 13.8 9.4 18 10 C 13.8 10.6 11.6 12.8 11 17 C 10.4 12.8 8.2 10.6 4 10 C 8.2 9.4 10.4 7.2 11 3 Z"),
            IconShape(path: "M 19 15 L 19 20 M 16.5 17.5 L 21.5 17.5"),
        ]),
        IconDefinition(id: "rune", name: "Rune circle", category: "Magic", shapes: [
            IconShape(path: "M 21 12 C 21 16.971 16.971 21 12 21 C 7.029 21 3 16.971 3 12 C 3 7.029 7.029 3 12 3 C 16.971 3 21 7.029 21 12 Z"),
            IconShape(path: "M 12 3.5 L 19.4 16.3 L 4.6 16.3 Z"),
            IconShape(path: "M 14 12 C 14 13.105 13.105 14 12 14 C 10.895 14 10 13.105 10 12 C 10 10.895 10.895 10 12 10 C 13.105 10 14 10.895 14 12 Z"),
        ]),
        IconDefinition(id: "flame", name: "Flame", category: "Magic", shapes: [
            IconShape(path: "M 12 2 C 14 6 19 8.5 19 14 C 19 17.866 15.866 21 12 21 C 8.134 21 5 17.866 5 14 C 5 10.5 7.2 8.5 8.5 6 C 9.3 7.8 10.3 8.8 11.5 9 C 11.8 6.5 11.5 4.4 12 2 Z"),
            IconShape(path: "M 12 21 C 10.343 21 9 19.657 9 18 C 9 16.2 10.4 15.2 12 13.5 C 13.6 15.2 15 16.2 15 18 C 15 19.657 13.657 21 12 21 Z"),
        ]),
        IconDefinition(id: "bolt", name: "Lightning bolt", category: "Magic", shapes: [
            IconShape(path: "M 13 2 L 4 14 L 11 14 L 10 22 L 19 10 L 12 10 Z"),
        ]),
        IconDefinition(id: "wizard-hat", name: "Wizard hat", category: "Magic", shapes: [
            IconShape(path: "M 5 19 L 11 3 C 12 7 14.5 9 18 10 L 14.5 12 L 17 19 Z"),
            IconShape(path: "M 3 19.5 C 6 20.5 18 20.5 21 19.5"),
            IconShape(path: "M 10 13 L 10.8 14.5 M 13 9.5 L 13.8 9.5"),
        ]),
        IconDefinition(id: "cauldron", name: "Cauldron", category: "Magic", shapes: [
            IconShape(path: "M 5 10 L 19 10 L 19 13 C 19 16.866 15.866 20 12 20 C 8.134 20 5 16.866 5 13 Z"),
            IconShape(path: "M 3.5 10 L 20.5 10"),
            IconShape(path: "M 8 20.5 L 9 18.7 M 16 20.5 L 15 18.7"),
            IconShape(path: "M 11.5 6 C 11.5 6.828 10.828 7.5 10 7.5 C 9.172 7.5 8.5 6.828 8.5 6 C 8.5 5.172 9.172 4.5 10 4.5 C 10.828 4.5 11.5 5.172 11.5 6 Z"),
            IconShape(path: "M 15 4 C 15 4.552 14.552 5 14 5 C 13.448 5 13 4.552 13 4 C 13 3.448 13.448 3 14 3 C 14.552 3 15 3.448 15 4 Z"),
        ]),
        IconDefinition(id: "dragon", name: "Dragon", category: "Creatures", shapes: [
            IconShape(path: "M 5 21 C 5 15 7 11.5 10 9 L 8 3 L 12.5 7 L 15 7 L 21 10 L 20 12.5 L 16 12.5 L 14 13.5 L 17.5 15 L 13 16 C 11.5 17 11 19 11 21"),
            IconShape(path: "M 15.5 9.2 C 15.5 9.752 15.052 10.2 14.5 10.2 C 13.948 10.2 13.5 9.752 13.5 9.2 C 13.5 8.648 13.948 8.2 14.5 8.2 C 15.052 8.2 15.5 8.648 15.5 9.2 Z", fill: true),
            IconShape(path: "M 8.5 14.5 C 6.5 13.5 4.5 14 3 15.5 M 7.8 17.5 C 6.2 17.1 4.6 17.5 3.3 18.7"),
        ]),
        IconDefinition(id: "skull", name: "Skull", category: "Creatures", shapes: [
            IconShape(path: "M 12 3 C 7.582 3 4 6.582 4 11 C 4 13.5 5.2 15.5 7 16.8 L 7 20 L 17 20 L 17 16.8 C 18.8 15.5 20 13.5 20 11 C 20 6.582 16.418 3 12 3 Z"),
            IconShape(path: "M 10.8 11.5 C 10.8 12.494 9.994 13.3 9 13.3 C 8.006 13.3 7.2 12.494 7.2 11.5 C 7.2 10.506 8.006 9.7 9 9.7 C 9.994 9.7 10.8 10.506 10.8 11.5 Z"),
            IconShape(path: "M 16.8 11.5 C 16.8 12.494 15.994 13.3 15 13.3 C 14.006 13.3 13.2 12.494 13.2 11.5 C 13.2 10.506 14.006 9.7 15 9.7 C 15.994 9.7 16.8 10.506 16.8 11.5 Z"),
            IconShape(path: "M 10 20 L 10 17.8 M 14 20 L 14 17.8 M 12 14.5 L 11 16.3 L 13 16.3 Z"),
        ]),
        IconDefinition(id: "ghost", name: "Ghost", category: "Creatures", shapes: [
            IconShape(path: "M 5 21 L 5 10 C 5 6.134 8.134 3 12 3 C 15.866 3 19 6.134 19 10 L 19 21 L 16.7 19 L 14.3 21 L 12 19 L 9.7 21 L 7.3 19 Z"),
            IconShape(path: "M 10.6 10 C 10.6 10.608 10.108 11.1 9.5 11.1 C 8.892 11.1 8.4 10.608 8.4 10 C 8.4 9.392 8.892 8.9 9.5 8.9 C 10.108 8.9 10.6 9.392 10.6 10 Z", fill: true),
            IconShape(path: "M 15.6 10 C 15.6 10.608 15.108 11.1 14.5 11.1 C 13.892 11.1 13.4 10.608 13.4 10 C 13.4 9.392 13.892 8.9 14.5 8.9 C 15.108 8.9 15.6 9.392 15.6 10 Z", fill: true),
        ]),
        IconDefinition(id: "bat", name: "Bat", category: "Creatures", shapes: [
            IconShape(path: "M 12 9 C 10 6.5 6 4.5 2 5.5 C 4 7.5 4.5 10.5 3.5 14 C 5.5 12.5 7.5 13 8.5 15 C 9.5 13.5 11 14 12 17 C 13 14 14.5 13.5 15.5 15 C 16.5 13 18.5 12.5 20.5 14 C 19.5 10.5 20 7.5 22 5.5 C 18 4.5 14 6.5 12 9 Z"),
            IconShape(path: "M 10.6 8.2 L 10.3 6.2 L 11.7 7.5 M 13.4 8.2 L 13.7 6.2 L 12.3 7.5"),
        ]),
        IconDefinition(id: "spider", name: "Spider", category: "Creatures", shapes: [
            IconShape(path: "M 15 14 C 15 15.657 13.657 17 12 17 C 10.343 17 9 15.657 9 14 C 9 12.343 10.343 11 12 11 C 13.657 11 15 12.343 15 14 Z"),
            IconShape(path: "M 13.8 9.3 C 13.8 10.294 12.994 11.1 12 11.1 C 11.006 11.1 10.2 10.294 10.2 9.3 C 10.2 8.306 11.006 7.5 12 7.5 C 12.994 7.5 13.8 8.306 13.8 9.3 Z"),
            IconShape(path: "M 12 2 L 12 7.5"),
            IconShape(path: "M 9.5 12.5 L 5 9.5 L 3 10.5 M 9.2 14 L 4 14 L 2 16 M 9.8 15.8 L 6.5 18 L 5.5 21 M 14.5 12.5 L 19 9.5 L 21 10.5 M 14.8 14 L 20 14 L 22 16 M 14.2 15.8 L 17.5 18 L 18.5 21"),
        ]),
        IconDefinition(id: "snake", name: "Snake", category: "Creatures", shapes: [
            IconShape(path: "M 17 6.5 C 15 4 11 4 10 7 C 9 10 12.5 11 14 13 C 15.5 15 13.5 18.5 10 19 C 6.5 19.5 4 18 3 17"),
            IconShape(path: "M 20 7.5 C 20 8.605 19.105 9.5 18 9.5 C 16.895 9.5 16 8.605 16 7.5 C 16 6.395 16.895 5.5 18 5.5 C 19.105 5.5 20 6.395 20 7.5 Z"),
            IconShape(path: "M 20 8 L 22 8.5 M 20 8.5 L 21.5 10"),
        ]),
        IconDefinition(id: "paw", name: "Paw print", category: "Creatures", shapes: [
            IconShape(path: "M 12 12.5 C 14.5 12.5 17 15.5 17 18 C 17 19.5 15.7 20.5 14 20.5 C 13 20.5 12.7 20 12 20 C 11.3 20 11 20.5 10 20.5 C 8.3 20.5 7 19.5 7 18 C 7 15.5 9.5 12.5 12 12.5 Z"),
            IconShape(path: "M 7.3 11 C 7.3 11.994 6.494 12.8 5.5 12.8 C 4.506 12.8 3.7 11.994 3.7 11 C 3.7 10.006 4.506 9.2 5.5 9.2 C 6.494 9.2 7.3 10.006 7.3 11 Z"),
            IconShape(path: "M 11 6.5 C 11 7.494 10.194 8.3 9.2 8.3 C 8.206 8.3 7.4 7.494 7.4 6.5 C 7.4 5.506 8.206 4.7 9.2 4.7 C 10.194 4.7 11 5.506 11 6.5 Z"),
            IconShape(path: "M 16.6 6.5 C 16.6 7.494 15.794 8.3 14.8 8.3 C 13.806 8.3 13 7.494 13 6.5 C 13 5.506 13.806 4.7 14.8 4.7 C 15.794 4.7 16.6 5.506 16.6 6.5 Z"),
            IconShape(path: "M 20.3 11 C 20.3 11.994 19.494 12.8 18.5 12.8 C 17.506 12.8 16.7 11.994 16.7 11 C 16.7 10.006 17.506 9.2 18.5 9.2 C 19.494 9.2 20.3 10.006 20.3 11 Z"),
        ]),
        IconDefinition(id: "claws", name: "Claw marks", category: "Creatures", shapes: [
            IconShape(path: "M 6 3 C 9 8 10 14 8 21 M 11.5 3 C 14.5 8 15.5 14 13.5 21 M 17 3 C 20 8 21 14 19 21"),
        ]),
        IconDefinition(id: "eye", name: "Eye", category: "Creatures", shapes: [
            IconShape(path: "M 2 12 C 2 12 5.5 5 12 5 C 18.5 5 22 12 22 12 C 22 12 18.5 19 12 19 C 5.5 19 2 12 2 12 Z"),
            IconShape(path: "M 15 12 C 15 13.657 13.657 15 12 15 C 10.343 15 9 13.657 9 12 C 9 10.343 10.343 9 12 9 C 13.657 9 15 10.343 15 12 Z"),
            IconShape(path: "M 13 12 C 13 12.552 12.552 13 12 13 C 11.448 13 11 12.552 11 12 C 11 11.448 11.448 11 12 11 C 12.552 11 13 11.448 13 12 Z", fill: true),
        ]),
        IconDefinition(id: "demon", name: "Demon", category: "Creatures", shapes: [
            IconShape(path: "M 19 14 C 19 17.866 15.866 21 12 21 C 8.134 21 5 17.866 5 14 C 5 10.134 8.134 7 12 7 C 15.866 7 19 10.134 19 14 Z"),
            IconShape(path: "M 6.8 9.5 L 4 3 L 9.2 7.4 M 17.2 9.5 L 20 3 L 14.8 7.4"),
            IconShape(path: "M 8.8 13 L 10.8 14 M 15.2 13 L 13.2 14 M 9.5 17.5 C 11 18.5 13 18.5 14.5 17.5"),
        ]),
        IconDefinition(id: "tentacle", name: "Tentacle", category: "Creatures", shapes: [
            IconShape(path: "M 3 21 C 3 15.5 6.5 12.5 11 11.5 C 15 10.5 16.5 8 15.7 5.7 C 14.9 3.5 12 3.4 11.4 5.3 C 11 6.6 12.2 7.7 13.4 6.9"),
            IconShape(path: "M 8.5 21 C 8.8 17.5 11 16 14 15 C 18.5 13.5 21 10 20 5.5 C 19.4 2.9 17.4 1.7 15 2"),
            IconShape(path: "M 8.3 18 C 8.3 18.442 7.942 18.8 7.5 18.8 C 7.058 18.8 6.7 18.442 6.7 18 C 6.7 17.558 7.058 17.2 7.5 17.2 C 7.942 17.2 8.3 17.558 8.3 18 Z"),
            IconShape(path: "M 11.3 14.8 C 11.3 15.242 10.942 15.6 10.5 15.6 C 10.058 15.6 9.7 15.242 9.7 14.8 C 9.7 14.358 10.058 14 10.5 14 C 10.942 14 11.3 14.358 11.3 14.8 Z"),
            IconShape(path: "M 15.3 12.8 C 15.3 13.242 14.942 13.6 14.5 13.6 C 14.058 13.6 13.7 13.242 13.7 12.8 C 13.7 12.358 14.058 12 14.5 12 C 14.942 12 15.3 12.358 15.3 12.8 Z"),
        ]),
        IconDefinition(id: "party", name: "Adventuring party", category: "People", shapes: [
            IconShape(path: "M 12.5 8 C 12.5 9.933 10.933 11.5 9 11.5 C 7.067 11.5 5.5 9.933 5.5 8 C 5.5 6.067 7.067 4.5 9 4.5 C 10.933 4.5 12.5 6.067 12.5 8 Z"),
            IconShape(path: "M 2 20 C 2 16.134 5.134 13 9 13 C 12.866 13 16 16.134 16 20"),
            IconShape(path: "M 16 4.5 C 17.933 4.5 19.5 6.067 19.5 8 C 19.5 9.933 17.933 11.5 16 11.5 M 18 13.5 C 20.501 14.685 22.069 17.233 22 20"),
        ]),
        IconDefinition(id: "hood", name: "Hooded rogue", category: "People", shapes: [
            IconShape(path: "M 12 3 C 8 3 6 6.5 6 10.5 L 6 14 C 6 15.5 4 16.5 3 18 L 3 21 L 21 21 L 21 18 C 20 16.5 18 15.5 18 14 L 18 10.5 C 18 6.5 16 3 12 3 Z"),
            IconShape(path: "M 9 13 C 9 9.5 10.3 7.5 12 7.5 C 13.7 7.5 15 9.5 15 13 C 14 14.5 13 15 12 15 C 11 15 10 14.5 9 13 Z"),
            IconShape(path: "M 11.5 11.6 C 11.5 11.987 11.187 12.3 10.8 12.3 C 10.413 12.3 10.1 11.987 10.1 11.6 C 10.1 11.213 10.413 10.9 10.8 10.9 C 11.187 10.9 11.5 11.213 11.5 11.6 Z", fill: true),
            IconShape(path: "M 13.9 11.6 C 13.9 11.987 13.587 12.3 13.2 12.3 C 12.813 12.3 12.5 11.987 12.5 11.6 C 12.5 11.213 12.813 10.9 13.2 10.9 C 13.587 10.9 13.9 11.213 13.9 11.6 Z", fill: true),
        ]),
        IconDefinition(id: "speech", name: "Dialogue", category: "People", shapes: [
            IconShape(path: "M 4 5 L 20 5 L 20 16 L 9.5 16 L 5 20 L 5 16 L 4 16 Z"),
            IconShape(path: "M 8 9 L 16 9 M 8 12 L 13 12"),
        ]),
        IconDefinition(id: "mask", name: "Theater mask", category: "People", shapes: [
            IconShape(path: "M 3 4 L 13 4 L 13 10 C 13 12.761 10.761 15 8 15 C 5.239 15 3 12.761 3 10 Z"),
            IconShape(path: "M 6 8 L 7 8 M 10 8 L 11 8 M 6.5 11.5 C 6.972 12.13 7.713 12.5 8.5 12.5 C 9.287 12.5 10.028 12.13 10.5 11.5"),
            IconShape(path: "M 15 8 L 21 8 L 21 14 C 21.015 16.073 19.751 17.94 17.82 18.694 C 15.89 19.449 13.694 18.934 12.3 17.4"),
            IconShape(path: "M 17 11 L 18 11 M 15.8 15.2 C 16.759 14.311 18.241 14.311 19.2 15.2"),
        ]),
        IconDefinition(id: "heart", name: "Heart", category: "People", shapes: [
            IconShape(path: "M 12 20 C 12 20 4 15 4 9 C 4.012 7.098 5.218 5.409 7.013 4.781 C 8.808 4.153 10.805 4.721 12 6.2 C 13.195 4.721 15.192 4.153 16.987 4.781 C 18.782 5.409 19.988 7.098 20 9 C 20 15 12 20 12 20 Z"),
        ]),
        IconDefinition(id: "laugh", name: "Laughing face", category: "People", shapes: [
            IconShape(path: "M 21 12 C 21 16.971 16.971 21 12 21 C 7.029 21 3 16.971 3 12 C 3 7.029 7.029 3 12 3 C 16.971 3 21 7.029 21 12 Z"),
            IconShape(path: "M 8 13.5 C 8.772 14.997 10.315 15.938 12 15.938 C 13.685 15.938 15.228 14.997 16 13.5 Z"),
            IconShape(path: "M 8 9.5 L 9.5 8.5 L 11 9.5 M 13 9.5 L 14.5 8.5 L 16 9.5"),
        ]),
        IconDefinition(id: "shock", name: "Shocked face", category: "People", shapes: [
            IconShape(path: "M 21 12 C 21 16.971 16.971 21 12 21 C 7.029 21 3 16.971 3 12 C 3 7.029 7.029 3 12 3 C 16.971 3 21 7.029 21 12 Z"),
            IconShape(path: "M 14 16 C 14 17.325 13.105 18.4 12 18.4 C 10.895 18.4 10 17.325 10 16 C 10 14.675 10.895 13.6 12 13.6 C 13.105 13.6 14 14.675 14 16 Z"),
            IconShape(path: "M 10.3 10 C 10.3 10.718 9.718 11.3 9 11.3 C 8.282 11.3 7.7 10.718 7.7 10 C 7.7 9.282 8.282 8.7 9 8.7 C 9.718 8.7 10.3 9.282 10.3 10 Z"),
            IconShape(path: "M 16.3 10 C 16.3 10.718 15.718 11.3 15 11.3 C 14.282 11.3 13.7 10.718 13.7 10 C 13.7 9.282 14.282 8.7 15 8.7 C 15.718 8.7 16.3 9.282 16.3 10 Z"),
            IconShape(path: "M 7.5 7 L 9.5 6 M 16.5 7 L 14.5 6"),
        ]),
        IconDefinition(id: "castle", name: "Castle", category: "Places", shapes: [
            IconShape(path: "M 3 21 L 3 8 L 5.5 8 L 5.5 10 L 8 10 L 8 8 L 10.5 8 L 10.5 12 L 13.5 12 L 13.5 8 L 16 8 L 16 10 L 18.5 10 L 18.5 8 L 21 8 L 21 21 Z"),
            IconShape(path: "M 10 21 L 10 17 C 10 15.895 10.895 15 12 15 C 13.105 15 14 15.895 14 17 L 14 21"),
        ]),
        IconDefinition(id: "tower", name: "Tower", category: "Places", shapes: [
            IconShape(path: "M 7 21 L 7 9 L 17 9 L 17 21"),
            IconShape(path: "M 6 9 L 6 4 L 8 4 L 8 6 L 10 6 L 10 4 L 14 4 L 14 6 L 16 6 L 16 4 L 18 4 L 18 9 Z"),
            IconShape(path: "M 12 12 L 12 14"),
            IconShape(path: "M 10 21 L 10 18 C 10 16.895 10.895 16 12 16 C 13.105 16 14 16.895 14 18 L 14 21"),
        ]),
        IconDefinition(id: "mug", name: "Tavern mug", category: "Places", shapes: [
            IconShape(path: "M 5 7 L 15 7 L 15 19 C 15 20.105 14.105 21 13 21 L 7 21 C 5.895 21 5 20.105 5 19 Z"),
            IconShape(path: "M 15 10 L 17 10 C 18.657 10 20 11.343 20 13 C 20 14.657 18.657 16 17 16 L 15 16"),
            IconShape(path: "M 4.5 7 C 4.44 6.187 4.736 5.389 5.312 4.812 C 5.889 4.236 6.687 3.94 7.5 4 C 7.994 3.286 8.773 2.821 9.636 2.725 C 10.499 2.629 11.361 2.912 12 3.5 C 12.973 3.318 13.973 3.628 14.672 4.328 C 15.372 5.027 15.682 6.027 15.5 7"),
            IconShape(path: "M 8.5 11 L 8.5 17 M 11.5 11 L 11.5 17"),
        ]),
        IconDefinition(id: "tent", name: "Tent", category: "Places", shapes: [
            IconShape(path: "M 2 20 L 12 4 L 22 20 Z"),
            IconShape(path: "M 9.5 20 L 12 14 L 14.5 20"),
            IconShape(path: "M 12 4 L 10.5 2 M 12 4 L 13.5 2"),
        ]),
        IconDefinition(id: "cave", name: "Cave", category: "Places", shapes: [
            IconShape(path: "M 2 20 C 3 14 6 8 12 6 C 18 8 21 14 22 20 Z"),
            IconShape(path: "M 8 20 C 8 16.5 10 13.5 12 13.5 C 14 13.5 16 16.5 16 20"),
        ]),
        IconDefinition(id: "mountain", name: "Mountain", category: "Places", shapes: [
            IconShape(path: "M 2 20 L 9 8 L 13 14 L 16 10 L 22 20 Z"),
            IconShape(path: "M 6.8 11.8 L 9 13 L 11 11.4"),
        ]),
        IconDefinition(id: "tree", name: "Tree", category: "Places", shapes: [
            IconShape(path: "M 12 21 L 12 15"),
            IconShape(path: "M 12 15 C 7.5 15 5 12.5 5 9 C 5 5.134 8.134 2 12 2 C 15.866 2 19 5.134 19 9 C 19 12.5 16.5 15 12 15 Z"),
            IconShape(path: "M 12 15 L 9.5 12.5 M 12 13.5 L 14 11.5"),
        ]),
        IconDefinition(id: "pine", name: "Pine forest", category: "Places", shapes: [
            IconShape(path: "M 12 2 L 7 9 L 10 9 L 6 15 L 10 15 L 6 20 L 18 20 L 14 15 L 18 15 L 14 9 L 17 9 Z"),
            IconShape(path: "M 12 20 L 12 22"),
        ]),
        IconDefinition(id: "ship", name: "Ship", category: "Places", shapes: [
            IconShape(path: "M 3 15 L 21 15 L 18.5 20 L 5.5 20 Z"),
            IconShape(path: "M 12 3 L 12 15"),
            IconShape(path: "M 12 4 L 18 12.5 L 12 12.5 M 12 6.5 L 7 12.5 L 12 12.5"),
        ]),
        IconDefinition(id: "temple", name: "Temple", category: "Places", shapes: [
            IconShape(path: "M 3 9 L 12 3 L 21 9 Z"),
            IconShape(path: "M 5.5 9 L 5.5 18 M 9.8 9 L 9.8 18 M 14.2 9 L 14.2 18 M 18.5 9 L 18.5 18"),
            IconShape(path: "M 3 21 L 21 21 M 4 18 L 20 18"),
        ]),
        IconDefinition(id: "map", name: "Map", category: "Places", shapes: [
            IconShape(path: "M 3 6 L 9 3 L 15 6 L 21 3 L 21 18 L 15 21 L 9 18 L 3 21 Z"),
            IconShape(path: "M 9 3 L 9 18 M 15 6 L 15 21"),
        ]),
        IconDefinition(id: "compass", name: "Compass", category: "Places", shapes: [
            IconShape(path: "M 21 12 C 21 16.971 16.971 21 12 21 C 7.029 21 3 16.971 3 12 C 3 7.029 7.029 3 12 3 C 16.971 3 21 7.029 21 12 Z"),
            IconShape(path: "M 15.5 8.5 L 13.5 13.5 L 8.5 15.5 L 10.5 10.5 Z"),
        ]),
        IconDefinition(id: "jolly-roger", name: "Pirate flag", category: "Places", shapes: [
            IconShape(path: "M 5 21 L 5 3"),
            IconShape(path: "M 5 4 L 19 4 L 19 14 L 5 14"),
            IconShape(path: "M 14.2 8 C 14.2 9.215 13.215 10.2 12 10.2 C 10.785 10.2 9.8 9.215 9.8 8 C 9.8 6.785 10.785 5.8 12 5.8 C 13.215 5.8 14.2 6.785 14.2 8 Z"),
            IconShape(path: "M 9 12.5 L 15 10.9 M 15 12.5 L 9 10.9"),
        ]),
        IconDefinition(id: "gate", name: "Dungeon gate", category: "Places", shapes: [
            IconShape(path: "M 4 21 L 4 9 C 4 5.686 7.582 3 12 3 C 16.418 3 20 5.686 20 9 L 20 21"),
            IconShape(path: "M 3 21 L 21 21 M 8 21 L 8 5.8 M 12 21 L 12 3 M 16 21 L 16 5.8 M 4 12 L 20 12 M 4 16.5 L 20 16.5"),
        ]),
        IconDefinition(id: "grave", name: "Grave", category: "Places", shapes: [
            IconShape(path: "M 6 21 L 6 9 C 6 5.686 8.686 3 12 3 C 15.314 3 18 5.686 18 9 L 18 21"),
            IconShape(path: "M 3 21 L 21 21"),
            IconShape(path: "M 12 8 L 12 15 M 9.5 10.5 L 14.5 10.5"),
        ]),
        IconDefinition(id: "sun", name: "Sun", category: "Nature", shapes: [
            IconShape(path: "M 16 12 C 16 14.209 14.209 16 12 16 C 9.791 16 8 14.209 8 12 C 8 9.791 9.791 8 12 8 C 14.209 8 16 9.791 16 12 Z"),
            IconShape(path: "M 12 2 L 12 4 M 12 20 L 12 22 M 4.9 4.9 L 6.3 6.3 M 17.7 17.7 L 19.1 19.1 M 2 12 L 4 12 M 20 12 L 22 12 M 4.9 19.1 L 6.3 17.7 M 17.7 6.3 L 19.1 4.9"),
        ]),
        IconDefinition(id: "moon", name: "Moon", category: "Nature", shapes: [
            IconShape(path: "M 20 14.5 C 16.995 15.784 13.511 15.111 11.2 12.8 C 8.889 10.489 8.216 7.005 9.5 4 C 5.563 5.119 2.983 8.884 3.36 12.96 C 3.737 17.035 6.965 20.263 11.04 20.64 C 15.116 21.017 18.881 18.437 20 14.5 Z"),
            IconShape(path: "M 17 3 L 17 6 M 15.5 4.5 L 18.5 4.5"),
        ]),
        IconDefinition(id: "rain", name: "Rain", category: "Nature", shapes: [
            IconShape(path: "M 7 14 C 4.515 14.11 2.41 12.185 2.3 9.7 C 2.19 7.215 4.115 5.11 6.6 5 C 7.465 2.811 9.628 1.415 11.979 1.528 C 14.33 1.641 16.349 3.238 17 5.5 C 19.347 5.5 21.25 7.403 21.25 9.75 C 21.25 12.097 19.347 14 17 14 Z"),
            IconShape(path: "M 8 17 L 7 20 M 12 16.5 L 10.7 21 M 16 17 L 15 20"),
        ]),
        IconDefinition(id: "storm", name: "Thunderstorm", category: "Nature", shapes: [
            IconShape(path: "M 7 14 C 4.515 14.11 2.41 12.185 2.3 9.7 C 2.19 7.215 4.115 5.11 6.6 5 C 7.465 2.811 9.628 1.415 11.979 1.528 C 14.33 1.641 16.349 3.238 17 5.5 C 19.347 5.5 21.25 7.403 21.25 9.75 C 21.25 12.097 19.347 14 17 14"),
            IconShape(path: "M 12.5 12 L 9.5 17 L 13.5 17 L 11 22"),
        ]),
        IconDefinition(id: "snowflake", name: "Snowflake", category: "Nature", shapes: [
            IconShape(path: "M 12 2 L 12 22 M 3.3 7 L 20.7 17 M 20.7 7 L 3.3 17"),
            IconShape(path: "M 9.5 3.5 L 12 6 L 14.5 3.5 M 9.5 20.5 L 12 18 L 14.5 20.5"),
        ]),
        IconDefinition(id: "wind", name: "Wind", category: "Nature", shapes: [
            IconShape(path: "M 3 8 L 14 8 C 15.657 8 17 6.657 17 5 C 17 3.343 15.657 2 14 2 C 12.343 2 11 3.343 11 5"),
            IconShape(path: "M 3 12 L 19 12 C 20.657 12 22 13.343 22 15 C 22 16.657 20.657 18 19 18 C 17.343 18 16 16.657 16 15"),
            IconShape(path: "M 3 16 L 10 16"),
        ]),
        IconDefinition(id: "wave", name: "Waves", category: "Nature", shapes: [
            IconShape(path: "M 2 7 C 4 5 6 5 8 7 C 10 9 12 9 14 7 C 16 5 18 5 20 7 M 2 12 C 4 10 6 10 8 12 C 10 14 12 14 14 12 C 16 10 18 10 20 12 M 2 17 C 4 15 6 15 8 17 C 10 19 12 19 14 17 C 16 15 18 15 20 17"),
        ]),
        IconDefinition(id: "mushroom", name: "Mushroom", category: "Nature", shapes: [
            IconShape(path: "M 3 12 C 3 7.582 7.029 4 12 4 C 16.971 4 21 7.582 21 12 Z"),
            IconShape(path: "M 9 12 L 9 18.5 C 9 20.157 10.343 21.5 12 21.5 C 13.657 21.5 15 20.157 15 18.5 L 15 12"),
            IconShape(path: "M 9.5 8.5 C 9.5 9.052 9.052 9.5 8.5 9.5 C 7.948 9.5 7.5 9.052 7.5 8.5 C 7.5 7.948 7.948 7.5 8.5 7.5 C 9.052 7.5 9.5 7.948 9.5 8.5 Z"),
            IconShape(path: "M 15 7 C 15 7.552 14.552 8 14 8 C 13.448 8 13 7.552 13 7 C 13 6.448 13.448 6 14 6 C 14.552 6 15 6.448 15 7 Z"),
        ]),
        IconDefinition(id: "campfire", name: "Campfire", category: "Nature", shapes: [
            IconShape(path: "M 4 20.5 L 20 16.5 M 4 16.5 L 20 20.5"),
            IconShape(path: "M 12 14.5 C 9.5 14.5 8 13 8 11 C 8 8.5 10 7.5 10.5 4.5 C 11.5 6 12 7 12 8 C 13 7 13.5 6 13.5 5 C 15.5 7 16 9 16 11 C 16 13 14.5 14.5 12 14.5 Z"),
        ]),
        IconDefinition(id: "volcano", name: "Volcano", category: "Nature", shapes: [
            IconShape(path: "M 2 21 L 8 11 L 16 11 L 22 21 Z"),
            IconShape(path: "M 10 11 L 9 8 M 14 11 L 15 8 M 12 9 L 12 5"),
            IconShape(path: "M 8.5 4 C 8.8 2.5 10.3 1.8 11.5 2.7 M 13 3 C 14 2 15.5 2.5 15.8 3.8"),
        ]),
        IconDefinition(id: "crown", name: "Crown", category: "Treasure", shapes: [
            IconShape(path: "M 3 8 L 7.5 12 L 12 5 L 16.5 12 L 21 8 L 19 19 L 5 19 Z"),
            IconShape(path: "M 5 19 L 19 19"),
        ]),
        IconDefinition(id: "key", name: "Key", category: "Treasure", shapes: [
            IconShape(path: "M 12 15.5 C 12 17.985 9.985 20 7.5 20 C 5.015 20 3 17.985 3 15.5 C 3 13.015 5.015 11 7.5 11 C 9.985 11 12 13.015 12 15.5 Z"),
            IconShape(path: "M 10.7 12.3 L 21 2 M 17 6 L 20 9 M 14.5 8.5 L 16.5 10.5"),
        ]),
        IconDefinition(id: "chest", name: "Treasure chest", category: "Treasure", shapes: [
            IconShape(path: "M 3 10 L 21 10 L 21 20 L 3 20 Z"),
            IconShape(path: "M 3 10 L 3 8 C 3 5.791 4.791 4 7 4 L 17 4 C 19.209 4 21 5.791 21 8 L 21 10"),
            IconShape(path: "M 10 10 L 10 13 L 14 13 L 14 10"),
        ]),
        IconDefinition(id: "coins", name: "Coins", category: "Treasure", shapes: [
            IconShape(path: "M 15 6.5 C 15 8.157 12.314 9.5 9 9.5 C 5.686 9.5 3 8.157 3 6.5 C 3 4.843 5.686 3.5 9 3.5 C 12.314 3.5 15 4.843 15 6.5 Z"),
            IconShape(path: "M 3 6.5 L 3 10.5 C 3 12.2 5.7 13.5 9 13.5 C 12.3 13.5 15 12.2 15 10.5 L 15 6.5"),
            IconShape(path: "M 9 14 L 9 17.5 C 9 19.2 11.7 20.5 15 20.5 C 18.3 20.5 21 19.2 21 17.5 L 21 13.5 C 21 11.9 18.6 10.6 15.5 10.5"),
        ]),
        IconDefinition(id: "gem", name: "Gem", category: "Treasure", shapes: [
            IconShape(path: "M 6 3 L 18 3 L 22 9 L 12 21 L 2 9 Z"),
            IconShape(path: "M 2 9 L 22 9 M 12 21 L 8 9 L 12 3 L 16 9 Z"),
        ]),
        IconDefinition(id: "bell", name: "Bell", category: "Treasure", shapes: [
            IconShape(path: "M 6 16 L 6 11 C 6 7.686 8.686 5 12 5 C 15.314 5 18 7.686 18 11 L 18 16 L 20 18 L 4 18 Z"),
            IconShape(path: "M 10 20.5 C 10 21.605 10.895 22.5 12 22.5 C 13.105 22.5 14 21.605 14 20.5"),
            IconShape(path: "M 12 5 L 12 3"),
        ]),
        IconDefinition(id: "candle", name: "Candle", category: "Treasure", shapes: [
            IconShape(path: "M 8 10 L 16 10 L 16 21 L 8 21 Z"),
            IconShape(path: "M 12 10 L 12 8"),
            IconShape(path: "M 12 6.5 C 10.7 5.5 10.7 3.8 12 2 C 13.3 3.8 13.3 5.5 12 6.5 Z"),
            IconShape(path: "M 5.5 21 L 18.5 21"),
        ]),
        IconDefinition(id: "lantern", name: "Lantern", category: "Treasure", shapes: [
            IconShape(path: "M 9 3 L 15 3 M 12 3 L 12 1 M 8 6 L 16 6 L 17 8 L 17 17 L 16 19 L 8 19 L 7 17 L 7 8 Z"),
            IconShape(path: "M 10 21.5 L 14 21.5"),
            IconShape(path: "M 12 10 C 10.8 11.2 10.8 12.8 12 14 C 13.2 12.8 13.2 11.2 12 10 Z"),
        ]),
        IconDefinition(id: "hourglass", name: "Hourglass", category: "Treasure", shapes: [
            IconShape(path: "M 6 2 L 18 2 M 6 22 L 18 22 M 7 2 C 7 8 12 9 12 12 C 12 15 7 16 7 22 M 17 2 C 17 8 12 9 12 12 C 12 15 17 16 17 22"),
        ]),
        IconDefinition(id: "torch", name: "Torch", category: "Treasure", shapes: [
            IconShape(path: "M 10 22 L 9 11 L 15 11 L 14 22 Z"),
            IconShape(path: "M 12 9 C 10 9 9 7.7 9 6 C 9 4 11 3 12 1 C 13 3 15 4 15 6 C 15 7.7 14 9 12 9 Z"),
        ]),
        IconDefinition(id: "war-horn", name: "War horn", category: "Treasure", shapes: [
            IconShape(path: "M 4 4 C 4 13 10 19 19 19"),
            IconShape(path: "M 5.8 4 C 6.6 11.5 11.3 15 20 14"),
            IconShape(path: "M 19 19 C 20.4 18 20.8 15.8 20 14"),
            IconShape(path: "M 4 4 L 5.8 4"),
            IconShape(path: "M 7.8 12.8 L 9.8 11.2 M 11.4 16.4 L 12.8 14.4"),
        ]),
        IconDefinition(id: "d20", name: "D20 die", category: "Treasure", shapes: [
            IconShape(path: "M 12 2 L 21 7 L 21 17 L 12 22 L 3 17 L 3 7 Z"),
            IconShape(path: "M 12 7 L 17 15 L 7 15 Z"),
            IconShape(path: "M 12 2 L 12 7 M 3 7 L 7 15 M 21 7 L 17 15 M 7 15 L 12 22 L 17 15"),
        ]),
        IconDefinition(id: "d6", name: "D6 die", category: "Treasure", shapes: [
            IconShape(path: "M 7 4 L 17 4 C 18.657 4 20 5.343 20 7 L 20 17 C 20 18.657 18.657 20 17 20 L 7 20 C 5.343 20 4 18.657 4 17 L 4 7 C 4 5.343 5.343 4 7 4 Z"),
            IconShape(path: "M 9.8 8.5 C 9.8 9.218 9.218 9.8 8.5 9.8 C 7.782 9.8 7.2 9.218 7.2 8.5 C 7.2 7.782 7.782 7.2 8.5 7.2 C 9.218 7.2 9.8 7.782 9.8 8.5 Z", fill: true),
            IconShape(path: "M 13.3 12 C 13.3 12.718 12.718 13.3 12 13.3 C 11.282 13.3 10.7 12.718 10.7 12 C 10.7 11.282 11.282 10.7 12 10.7 C 12.718 10.7 13.3 11.282 13.3 12 Z", fill: true),
            IconShape(path: "M 16.8 15.5 C 16.8 16.218 16.218 16.8 15.5 16.8 C 14.782 16.8 14.2 16.218 14.2 15.5 C 14.2 14.782 14.782 14.2 15.5 14.2 C 16.218 14.2 16.8 14.782 16.8 15.5 Z", fill: true),
        ]),
        IconDefinition(id: "question", name: "Mystery", category: "Treasure", shapes: [
            IconShape(path: "M 21 12 C 21 16.971 16.971 21 12 21 C 7.029 21 3 16.971 3 12 C 3 7.029 7.029 3 12 3 C 16.971 3 21 7.029 21 12 Z"),
            IconShape(path: "M 9.5 9 C 9.504 7.753 10.428 6.699 11.664 6.531 C 12.9 6.364 14.071 7.133 14.407 8.334 C 14.744 9.535 14.143 10.801 13 11.3 C 12.4 11.6 12 12.2 12 12.9 L 12 13.5"),
            IconShape(path: "M 12.9 17 C 12.9 17.497 12.497 17.9 12 17.9 C 11.503 17.9 11.1 17.497 11.1 17 C 11.1 16.503 11.503 16.1 12 16.1 C 12.497 16.1 12.9 16.503 12.9 17 Z", fill: true),
        ]),
        IconDefinition(id: "note", name: "Music", category: "Music", shapes: [
            IconShape(path: "M 9 18 L 9 5 L 20 3 L 20 16"),
            IconShape(path: "M 9 18 C 9 19.381 7.881 20.5 6.5 20.5 C 5.119 20.5 4 19.381 4 18 C 4 16.619 5.119 15.5 6.5 15.5 C 7.881 15.5 9 16.619 9 18 Z"),
            IconShape(path: "M 20 16 C 20 17.381 18.881 18.5 17.5 18.5 C 16.119 18.5 15 17.381 15 16 C 15 14.619 16.119 13.5 17.5 13.5 C 18.881 13.5 20 14.619 20 16 Z"),
        ]),
        IconDefinition(id: "speaker", name: "Speaker", category: "Music", shapes: [
            IconShape(path: "M 4 9 L 8 9 L 13 5 L 13 19 L 8 15 L 4 15 Z"),
            IconShape(path: "M 16.5 8.5 C 18.406 10.444 18.406 13.556 16.5 15.5 M 19 6 C 22.306 9.317 22.306 14.683 19 18"),
        ]),
        IconDefinition(id: "drum", name: "Drum", category: "Music", shapes: [
            IconShape(path: "M 20 8 C 20 9.657 16.418 11 12 11 C 7.582 11 4 9.657 4 8 C 4 6.343 7.582 5 12 5 C 16.418 5 20 6.343 20 8 Z"),
            IconShape(path: "M 4 8 L 4 17 C 4 18.7 7.6 20 12 20 C 16.4 20 20 18.7 20 17 L 20 8"),
            IconShape(path: "M 4 8 L 9 19.5 M 20 8 L 15 19.5"),
            IconShape(path: "M 15 2.5 L 19.5 5.5 M 9 2.5 L 4.5 5.5"),
        ]),
        IconDefinition(id: "lute", name: "Lute", category: "Music", shapes: [
            IconShape(path: "M 14 10 C 16.154 12.154 16.154 15.646 14 17.8 C 11.846 19.954 8.354 19.954 6.2 17.8 C 4 15.6 4.5 12 7.5 10.5 C 9.5 9.5 12 8 14 10 Z"),
            IconShape(path: "M 13 11 L 20 4 M 18.5 2.5 L 21.5 5.5"),
            IconShape(path: "M 11.5 14 C 11.5 14.828 10.828 15.5 10 15.5 C 9.172 15.5 8.5 14.828 8.5 14 C 8.5 13.172 9.172 12.5 10 12.5 C 10.828 12.5 11.5 13.172 11.5 14 Z"),
        ]),
        IconDefinition(id: "play", name: "Play", category: "Interface", shapes: [
            IconShape(path: "M 7 4 L 20 12 L 7 20 Z"),
        ]),
        IconDefinition(id: "stop", name: "Stop", category: "Interface", shapes: [
            IconShape(path: "M 7.5 6 L 16.5 6 C 17.328 6 18 6.672 18 7.5 L 18 16.5 C 18 17.328 17.328 18 16.5 18 L 7.5 18 C 6.672 18 6 17.328 6 16.5 L 6 7.5 C 6 6.672 6.672 6 7.5 6 Z"),
        ]),
        IconDefinition(id: "repeat", name: "Repeat", category: "Interface", shapes: [
            IconShape(path: "M 17 2 L 20 5 L 17 8"),
            IconShape(path: "M 4 11 L 4 9 C 4 6.791 5.791 5 8 5 L 20 5"),
            IconShape(path: "M 7 22 L 4 19 L 7 16"),
            IconShape(path: "M 20 13 L 20 15 C 20 17.209 18.209 19 16 19 L 4 19"),
        ]),
        IconDefinition(id: "scissors", name: "Clip", category: "Interface", shapes: [
            IconShape(path: "M 9 6 C 9 7.657 7.657 9 6 9 C 4.343 9 3 7.657 3 6 C 3 4.343 4.343 3 6 3 C 7.657 3 9 4.343 9 6 Z"),
            IconShape(path: "M 9 18 C 9 19.657 7.657 21 6 21 C 4.343 21 3 19.657 3 18 C 3 16.343 4.343 15 6 15 C 7.657 15 9 16.343 9 18 Z"),
            IconShape(path: "M 8.2 7.8 L 20 19 M 8.2 16.2 L 20 5"),
        ]),
        IconDefinition(id: "layers", name: "Ambience", category: "Interface", shapes: [
            IconShape(path: "M 12 3 L 21 8 L 12 13 L 3 8 Z"),
            IconShape(path: "M 3 12.5 L 12 17.5 L 21 12.5"),
            IconShape(path: "M 3 17 L 12 22 L 21 17"),
        ]),
        IconDefinition(id: "grid", name: "All", category: "Interface", shapes: [
            IconShape(path: "M 4.5 3 L 8.5 3 C 9.328 3 10 3.672 10 4.5 L 10 8.5 C 10 9.328 9.328 10 8.5 10 L 4.5 10 C 3.672 10 3 9.328 3 8.5 L 3 4.5 C 3 3.672 3.672 3 4.5 3 Z"),
            IconShape(path: "M 15.5 3 L 19.5 3 C 20.328 3 21 3.672 21 4.5 L 21 8.5 C 21 9.328 20.328 10 19.5 10 L 15.5 10 C 14.672 10 14 9.328 14 8.5 L 14 4.5 C 14 3.672 14.672 3 15.5 3 Z"),
            IconShape(path: "M 4.5 14 L 8.5 14 C 9.328 14 10 14.672 10 15.5 L 10 19.5 C 10 20.328 9.328 21 8.5 21 L 4.5 21 C 3.672 21 3 20.328 3 19.5 L 3 15.5 C 3 14.672 3.672 14 4.5 14 Z"),
            IconShape(path: "M 15.5 14 L 19.5 14 C 20.328 14 21 14.672 21 15.5 L 21 19.5 C 21 20.328 20.328 21 19.5 21 L 15.5 21 C 14.672 21 14 20.328 14 19.5 L 14 15.5 C 14 14.672 14.672 14 15.5 14 Z"),
        ]),
        IconDefinition(id: "tag", name: "Tag", category: "Interface", shapes: [
            IconShape(path: "M 3 12 L 3 4 C 3 3.448 3.448 3 4 3 L 12 3 L 21 12 L 12 21 Z"),
            IconShape(path: "M 9 7.5 C 9 8.328 8.328 9 7.5 9 C 6.672 9 6 8.328 6 7.5 C 6 6.672 6.672 6 7.5 6 C 8.328 6 9 6.672 9 7.5 Z"),
        ]),
        IconDefinition(id: "search", name: "Search", category: "Interface", shapes: [
            IconShape(path: "M 18 11 C 18 14.866 14.866 18 11 18 C 7.134 18 4 14.866 4 11 C 4 7.134 7.134 4 11 4 C 14.866 4 18 7.134 18 11 Z"),
            IconShape(path: "M 20 20 L 16 16"),
        ]),
        IconDefinition(id: "plus", name: "Add", category: "Interface", shapes: [
            IconShape(path: "M 12 5 L 12 19 M 5 12 L 19 12"),
        ]),
        IconDefinition(id: "close", name: "Close", category: "Interface", shapes: [
            IconShape(path: "M 6 6 L 18 18 M 18 6 L 6 18"),
        ]),
        IconDefinition(id: "edit", name: "Edit", category: "Interface", shapes: [
            IconShape(path: "M 4 20 L 8 20 L 19 9 L 15 5 L 4 16 Z"),
            IconShape(path: "M 13.5 6.5 L 17.5 10.5"),
        ]),
        IconDefinition(id: "trash", name: "Delete", category: "Interface", shapes: [
            IconShape(path: "M 4 7 L 20 7 M 10 11 L 10 17 M 14 11 L 14 17 M 5 7 L 6 20 L 18 20 L 19 7 M 9 7 L 9 4 L 15 4 L 15 7"),
        ]),
        IconDefinition(id: "download", name: "Download", category: "Interface", shapes: [
            IconShape(path: "M 12 3 L 12 15 M 7 10 L 12 15 L 17 10 M 4 20 L 20 20"),
        ]),
        IconDefinition(id: "video", name: "Video", category: "Interface", shapes: [
            IconShape(path: "M 6 5 L 18 5 C 20.209 5 22 6.791 22 9 L 22 15 C 22 17.209 20.209 19 18 19 L 6 19 C 3.791 19 2 17.209 2 15 L 2 9 C 2 6.791 3.791 5 6 5 Z"),
            IconShape(path: "M 10 9 L 15 12 L 10 15 Z"),
        ]),
        IconDefinition(id: "folder", name: "Folder", category: "Interface", shapes: [
            IconShape(path: "M 3 6 C 3 5.448 3.448 5 4 5 L 9 5 L 11 7 L 20 7 C 20.552 7 21 7.448 21 8 L 21 18 C 21 18.552 20.552 19 20 19 L 4 19 C 3.448 19 3 18.552 3 18 Z"),
        ]),
        IconDefinition(id: "more", name: "More", category: "Interface", shapes: [
            IconShape(path: "M 6.4 12 C 6.4 12.773 5.773 13.4 5 13.4 C 4.227 13.4 3.6 12.773 3.6 12 C 3.6 11.227 4.227 10.6 5 10.6 C 5.773 10.6 6.4 11.227 6.4 12 Z", fill: true),
            IconShape(path: "M 13.4 12 C 13.4 12.773 12.773 13.4 12 13.4 C 11.227 13.4 10.6 12.773 10.6 12 C 10.6 11.227 11.227 10.6 12 10.6 C 12.773 10.6 13.4 11.227 13.4 12 Z", fill: true),
            IconShape(path: "M 20.4 12 C 20.4 12.773 19.773 13.4 19 13.4 C 18.227 13.4 17.6 12.773 17.6 12 C 17.6 11.227 18.227 10.6 19 10.6 C 19.773 10.6 20.4 11.227 20.4 12 Z", fill: true),
        ]),
    ]

    static let fromEmoji: [String: String] = [
        "⚔️": "crossed-swords",
        "🐉": "dragon",
        "🍺": "mug",
        "🔥": "flame",
        "🌲": "pine",
        "🏰": "castle",
        "💀": "skull",
        "🌊": "wave",
        "⚡": "bolt",
        "🎲": "d20",
        "🧙": "wizard-hat",
        "🌙": "moon",
        "👑": "crown",
        "🕯️": "candle",
        "🗡️": "dagger",
        "🛡️": "shield",
        "🐺": "paw",
        "👻": "ghost",
        "⛈️": "storm",
        "🎻": "lute",
        "🗺️": "map",
        "🏴‍☠️": "jolly-roger",
        "🎭": "mask",
    ]
}
